name: Build svelte app

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
      - name: Config name
        run: |
          git config --global user.name "Raphael"
      - name: Config email
        run: |         
          git config --global user.email "raphael@wayoff.ch"
      - name: Checkout
        run: git checkout -b deploy
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Cleanup
        run: |
          rm -r .gitignore
      - name: Change to build folder
        run: |
          cd .svelte-kit/
      - name: Add
        run: |
          git add .
      - name: Commit
        run: |
          git commit -m 'deploy'
      - name: Push
        run: |
          git push -f origin deploy
        shell: bash

