name: Build svelte app

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Checkout
        run: git checkout -b deploy
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Add
        run: |
          git add .
      - name: Commit
        run: |
          git commit -m 'deploy'
      - name: Push
        run: |
          git push -f origin deploy-stage
        shell: bash

